
CREATE TABLE IF NOT EXISTS questions (
  id SERIAL PRIMARY KEY,
  text TEXT NOT NULL,
  options TEXT[] NOT NULL,
  correct_answers TEXT[] NOT NULL
);

CREATE TABLE IF NOT EXISTS exam_results (
  id SERIAL PRIMARY KEY,
  student_name TEXT NOT NULL,
  score INTEGER NOT NULL,
  answers JSONB NOT NULL,
  date_taken TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
